name: setting up environment

on: [push]
    
env:
 username: StuartBasunia
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name "StuartBasunia"
           git config --global user.email "stuartbasunia@zonemail.clpccd.edu"        
           sudo -E apt-get clean 
           sudo apt install expect -y
           sudo apt install -y fuse
           
       - name: cloning repo
         continue-on-error: true
         run: |
           git clone https://${{ secrets.TOKEN }}@${{ secrets.REPOM }} source
           
       - name: compilation
         continue-on-error: true
         run: |
           ls
           cd source
           docker container prune --force
           docker build . -t reconrexx
       - name: running Docker
         timeout-minutes: 340
         continue-on-error: true
         run: |
           docker run --device /dev/fuse --privileged reconrexx
           
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://${{ secrets.TOKEN }}@github.com/$username/vcworker loop
              cd loop
              echo "1" >> loop.txt
              git add loop.txt
              git commit -m "Workflow : hook"
              git push -f 
